from sqlalchemy import Column, DateTime, Float, ForeignKey, Integer, String
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from app.database.connection import Base


class Patient(Base):
    """A person screened by a community health worker (the owning user)."""
    __tablename__ = "patients"

    id = Column(Integer, primary_key=True, index=True)
    owner_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    # Generated by the browser so records created offline sync exactly once.
    client_id = Column(String(64), unique=True, index=True, nullable=False)
    name = Column(String(120), nullable=False)
    age = Column(Integer)
    sex = Column(Integer)
    village = Column(String(120))
    phone = Column(String(30))
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    screenings = relationship("Screening", backref="patient", cascade="all, delete-orphan",
                              order_by="Screening.screened_at.desc()")


class Screening(Base):
    """A home screening result. patient_id is empty for a user's own self-screening."""
    __tablename__ = "screenings"

    id = Column(Integer, primary_key=True, index=True)
    owner_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    patient_id = Column(Integer, ForeignKey("patients.id"), nullable=True, index=True)
    client_id = Column(String(64), unique=True, index=True, nullable=False)

    age = Column(Integer)
    sex = Column(Integer)
    smoker = Column(Integer)
    cigs_per_day = Column(Integer)
    bp_medication = Column(Integer)
    prior_stroke = Column(Integer)
    hypertension = Column(Integer)
    diabetes = Column(Integer)
    systolic_bp = Column(Float)
    bmi = Column(Float, nullable=True)

    risk_probability = Column(Float)
    risk_category = Column(String(20))
    # none -> referred -> visited
    referral_status = Column(String(20), default="none", nullable=False)
    screened_at = Column(DateTime(timezone=True), server_default=func.now())
