import { ArrowRight, CheckCircle2 } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useState } from 'react';
import { AuthLayout } from './Login';
import { requestPasswordReset, resetPassword } from '../services/api';

export default function ForgotPassword() {
  const [email, setEmail] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const submit = async (event) => { event.preventDefault(); setError(''); setMessage(''); setLoading(true); try { const result = await requestPasswordReset(email); setMessage(result.message); } catch (requestError) { setError(requestError.response?.data?.detail || 'Unable to process your request right now.'); } finally { setLoading(false); } };
  return <AuthLayout title="Reset your password" subtitle="We will send a secure reset link to your email."><form className="auth-form" onSubmit={submit}><label className="auth-field"><span>Email address</span><input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@example.com" /></label>{message && <div className="form-success"><CheckCircle2 size={15} />{message}</div>}{error && <div className="form-error">{error}</div>}<button className="btn btn-primary auth-submit" disabled={loading}>{loading ? 'Sending...' : 'Send reset link'} <ArrowRight size={17} /></button><p className="auth-switch"><Link to="/login">Back to sign in</Link></p></form></AuthLayout>;
}

export function ResetPassword() {
  const token = new URLSearchParams(window.location.hash.split('?')[1] || '').get('token') || '';
  const [form, setForm] = useState({ password: '', confirm_password: '' }); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const [done, setDone] = useState(false);
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async (event) => { event.preventDefault(); setError(''); if (!token) { setError('This password reset link is invalid or expired.'); return; } if (form.password.length < 8) { setError('Password must be at least 8 characters.'); return; } if (form.password !== form.confirm_password) { setError('Passwords do not match.'); return; } setLoading(true); try { await resetPassword({ token, ...form }); setDone(true); setTimeout(() => { window.location.hash = '#/login'; }, 1400); } catch (requestError) { setError(requestError.response?.data?.detail || 'This password reset link is invalid or expired.'); } finally { setLoading(false); } };
  return <AuthLayout title="Choose a new password" subtitle="Create a new password for your CardioGuard account."><form className="auth-form" onSubmit={submit}><label className="auth-field"><span>New password</span><input required minLength="8" type="password" value={form.password} onChange={(event) => update('password', event.target.value)} placeholder="8+ characters" /></label><label className="auth-field"><span>Confirm password</span><input required minLength="8" type="password" value={form.confirm_password} onChange={(event) => update('confirm_password', event.target.value)} placeholder="Repeat password" /></label>{done && <div className="form-success"><CheckCircle2 size={15} />Password reset successfully. Redirecting to sign in...</div>}{error && <div className="form-error">{error}</div>}<button className="btn btn-primary auth-submit" disabled={loading || done}>{loading ? 'Resetting...' : 'Reset password'} <ArrowRight size={17} /></button><p className="auth-switch"><Link to="/login">Back to sign in</Link></p></form></AuthLayout>;
}